ALTER TABLE vacations
  ADD COLUMN IF NOT EXISTS salario_base NUMERIC,
  ADD COLUMN IF NOT EXISTS dias_ferias INTEGER,
  ADD COLUMN IF NOT EXISTS dias_abono INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS valor_ferias NUMERIC,
  ADD COLUMN IF NOT EXISTS valor_terco_constitucional NUMERIC,
  ADD COLUMN IF NOT EXISTS valor_abono_pecuniario NUMERIC,
  ADD COLUMN IF NOT EXISTS valor_terco_abono NUMERIC,
  ADD COLUMN IF NOT EXISTS descontos_inss NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS descontos_irrf NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS valor_liquido NUMERIC;

ALTER TABLE bills
  ADD COLUMN IF NOT EXISTS vacation_id UUID;
